# Explore State Vaccination Rates

In [6]:
import matplotlib.pyplot as plt
import json
import os
import datetime
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import metrics
data_dir = './vaccine_data/hhs_data/'

In [7]:
%%javascript
IPython.OutputArea.auto_scroll_threshold = 999;

In [8]:
train_years = ['2013','2014']
dev_years = ['2015']
test_years = ['2016','2017']

train_download_dir = ('train',train_years)
dev_download_dir = ('dev',dev_years)
test_download_dir = ('test',test_years)
data_split_ls = [train_download_dir,dev_download_dir,test_download_dir]

In [9]:
def convert_to_calender_data(week_offset_from_aug_1,year):
    '''Returns the calender Week'''
    d = "{}-W{}".format(year,week_offset_from_aug_1+31)
    r = datetime.datetime.strptime(d + '-0', "%Y-W%W-%w")
    r = r.strftime("%B %d, %Y")    
    return r

In [42]:
#output_format = "Year:{}\tState:{}\tState_code{}\tCount:{}\tPercentage:{}"

output_format="{},{},{},{},{}\n"
output_file = open("state_final_rates.csv","w") 
output_file.write("Year,State,State_OCount,Percentage\n")
state_list = os.listdir(data_dir+'train/2013')
for state in state_list:
    for data_split in data_split_ls:
        split,years = data_split
        for year in years:
            data = pd.read_json(open(os.path.join(data_dir,split,year,state)))
            str_output = output_format.format(data.iloc[-1]['year'],
                                          data.iloc[-1]['name'],data.iloc[-1]['short_name'],
                                              data.iloc[-1]['count'],data.iloc[-1]['percentage'])
            output_file.write(str_output)
output_file.close()

In [43]:
data

,count,disparity,ethnicity,fips,medicare_status,name,percentage,short_name,week,week_start,year
0,88926,0,T,44,A,Rhode Island,0.001889,RI,1,05AUG,2017
1,88926,0,T,44,A,Rhode Island,0.006567,RI,2,12AUG,2017
2,88926,0,T,44,A,Rhode Island,0.010975,RI,3,19AUG,2017
3,88926,0,T,44,A,Rhode Island,0.017959,RI,4,26AUG,2017
4,88926,0,T,44,A,Rhode Island,0.032375,RI,5,02SEP,2017
5,88926,0,T,44,A,Rhode Island,0.059589,RI,6,09SEP,2017
6,88926,0,T,44,A,Rhode Island,0.092403,RI,7,16SEP,2017
7,88926,0,T,44,A,Rhode Island,0.135708,RI,8,23SEP,2017
8,88926,0,T,44,A,Rhode Island,0.193026,RI,9,30SEP,2017
9,88926,0,T,44,A,Rhode Island,0.242359,RI,10,07OCT,2017
10,88926,0,T,44,A,Rhode Island,0.296786,RI,11,14OCT,2017
11,88926,0,T,44,A,Rhode Island,0.340946,RI,12,21OCT,2017
12,88926,0,T,44,A,Rhode Island,0.371601,RI,13,28OCT,2017
13,88926,0,T,44,A,Rhode Island,0.400142,RI,14,04NOV,2017
14,88926,0,T,44,A,Rhode Island,0.423127,RI,15,11NOV,2017
15,88926,0,T,44,A,Rhode Island,0.434496,RI,16,18NOV,2017
16,88926,0,T,44,A,Rhode Island,0.449520,RI,17,25NOV,2017
17,88926,0,T,44,A,Rhode Island,0.463531,RI,18,02DEC,2017
18,88926,0,T,44,A,Rhode Island,0.473990,RI,19,09DEC,2017
19,88926,0,T,44,A,Rhode Island,0.480309,RI,20,16DEC,2017
20,88926,0,T,44,A,Rhode Island,0.483233,RI,21,23DEC,2017
21,88926,0,T,44,A,Rhode Island,0.484695,RI,22,30DEC,2017
22,88926,0,T,44,A,Rhode Island,0.485775,RI,23,06JAN,2017
23,88926,0,T,44,A,Rhode Island,0.485775,RI,24,13JAN,2017
24,88926,0,T,44,A,Rhode Island,0.485775,RI,25,20JAN,2017